"""empty message

Revision ID: 2bbc9107a387
Revises: None
Create Date: 2016-05-29 01:04:25.443000

"""

# revision identifiers, used by Alembic.
revision = '2bbc9107a387'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('date_added', sa.String(), nullable=True))
    op.add_column('recipes', sa.Column('rating', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipes', 'rating')
    op.drop_column('recipes', 'date_added')
    ### end Alembic commands ###
