"""empty message

Revision ID: f96f7ae2cd1d
Revises: 2bbc9107a387
Create Date: 2016-06-03 21:14:50.575000

"""

# revision identifiers, used by Alembic.
revision = 'f96f7ae2cd1d'
down_revision = '2bbc9107a387'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'ingredients', ['name'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ingredients', type_='unique')
    ### end Alembic commands ###
